### ISSUE TITLE
Some questions about loading i2b2 data

### ISSUE THREAD

**Issue by lvcheng1031** [thehyve/transmart-batch#50]
My transmart-batch version is the latest.
My Transmart version is 1.2.4, which is the virtual machine image. The database is postgresql.
The dataset is provided by this project. And the path is studies\I2B2SAMPLE.
The command for importing is :
./gradlew run -Pargs='-p studies/I2B2SAMPLE/i2b2.params -n' –debug
And the build process will fail because of the following reason

[system.out] org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO i2b2demodata.observation_fact (encounter_num, patient_num, concept_cd, provider_id, start_date, modifier_cd, instance_num, valtype_cd, tval_char, nval_num, valueflag_cd, units_cd, end_date, observation_blob, update_date, download_date, import_date, sourcesystem_cd, upload_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; ERROR: duplicate key value violates unique constraint "observation_fact_pkey"

If I delete 
‘main_data.tsv	7	true	CON:C1-TEXT	text	
main_data.tsv	15	false	MOD:1	text’
or
‘main_data.tsv	7	true	CON:C1-TEXT	text	
main_data.tsv	16	false	MOD:1	text	‘
in the column_map file, the process can success. But the entries aren’t created in the table_access table.

If I import the studies\I2B2SAMPLE_INCR, to test the incremental model. Then there will be the following output:

[QUIET] [system.out] org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [
                SELECT
                    patient_ide,
                    patient_num
                FROM i2b2demodata.patient_mapping
                WHERE
                    patient_ide IN (?, ?)
                    AND patient_ide_source = ?
                    AND project_id = ?]; nested exception is org.postgresql.util.PSQLException: ERROR: column "project_id" does not exist

**Comment by cataphract** [comment]
The i2b2 job is for importing into i2b2 1.7, not transmart.
